extra/python3-colcon-common-extensions: remove load-limting option (#503)
* fix(extra/python3-colcon-common-extensions): remove load-limting option

problem:
    By default colcon-cmake tries to build with load-averaging using
    `make -l` (far enough under the hood) which leads to very verbose
    build logs complaining that "gmake[1]: cannot enforce load limit:
    getloadavg: Function not implemented". There isn't much to it beyond
    that our libc does not implement `getloadavg` so we dont support
    `-l` option for builds.

Solution:
    By the small sliver of chance that we end up supporting this function
    down the line, try except os.getloadavg. If AttributeError is thrown
    skip returning `f'-l{jobs}'.

    In order to apply 0000-colcon-cmake-getloadavg.patch I added
    prepare() which includes _apply_qnx_patch(); this was stolen from
    our exisiting ros packages in order to maintain consistency with how
    we apply patches in metapkges

* fix(extra/python3-colcon-common-extensions): clean patch for getloadavg

problem:
    As per @eleir9268's and @jscaff's review(s) if the intent of the try
    except block is to allow for future load-balancing (if it is
    supported) then the the cleaner way to do this is to check if
    `getloadavg` in `os.__dict__`.

solution:
    keeping the original code as clean as possible, just check if
    getloadavg is not in the dictionary, and early return without
    `f'-l{jobs}'`

Co-authored-by: @eleir9268